<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Sniff_Stay.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SniffAndStay.Application\SniffAndStay.Application.csproj" />
    <ProjectReference Include="..\SniffAndStay.Infrastructure\SniffAndStay.Infrastructure.csproj" />
  </ItemGroup>

</Project>
